### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by metropt** [luspi/photoqt-dev#35]
Hi,
Did you try to run it on OSX? Do you use any library or is it pure Qt?

thank you

**Comment by luspi** [comment]
Hi @metropt 

I haven't tried running it on OSX (since I don't have access to it), but it should be no problem getting it to work on it. PhotoQT is purely based on Qt and no platform specific libraries. It does make use of Exiv2 and GraphicsMagick (which both I think are also available for OSX), but these dependencies are not crucial (they add some nice features to PhotoQt though) and they can be disabled via cmake (see the README file).

If you get a chance to give it go, let me know how you get on!

Regards
Lukas

**Comment by metropt** [comment]
Hi @luspi 
I'll try to compile it and will give you some feedback :)

**Comment by metropt** [comment]
Was able to compile but it doesn't look to work properly. I'll run it on windows or linux to see how it usually work :)

**Comment by luspi** [comment]
Did you get a chance to run it on Windows/Linux? What exactly do you mean by "doesn't look to work properly?

**Comment by metropt** [comment]
Just tried it on windows and it looks ok will try to record it working on mac so you can see what I mean.

**Comment by luspi** [comment]
Okay, thanks a million!

**Comment by metropt** [comment]
http://we.tl/VofsihNb2K have a look

**Comment by luspi** [comment]
Thanks a million!

A few things I noticed:
- It seems like fake transparency doesn't work properly (there could be a conflict between some Mac animation and PhotoQt taking the screenshot). Try enabling real transparency in the settings (tab "Look and Behaviour", sub tab "Advanced")...
- The 'Open File' dialog appears to be behind PhotoQt, which kinda defeats its purpose... There is a setting so that PhotoQt doesn't try to force itself into the foreground, though (as I just noticed) there isn't actually an option in the settings window to change it. However, in the settings file (should be located at [HOME]/.photoqt/settings), if you change the line "KeepOnTop=1" to "KeepOnTop=0", that should take care of this problem.
- After clicking the tray icon, PhotoQt should hide completely, however, for some reason you're left with a black rectangle... If you go into the settings, in the very first tab that opens, enable "Hide to system tray". Then try to close PhotoQt and see if it properly hides and doesn't leave a black rectangle behind (you can still quit PhotoQt fully by using the default shortcut "q").

Let me know, if the above does anything to help...

**Comment by luspi** [comment]
PhotoQt is moving away from GitHub to GitLab ([more info](http://photoqt.org/news/1434375887)). This issue is duplicated here: https://gitlab.com/luspi/photoqt-legacy/issues
