### ISSUE TITLE
Start menu folder and desktop entry not created

### ISSUE THREAD

**Issue by smarquespt** [luspi/photoqt-dev#37]
When finishing the installer we see a dialog saying if we want to create a strt menu entry and a desktop entry. But even with checkbox enabled those 2 items are not created.

I´m using 1.2 release on w7 64 bits

**Comment by luspi** [comment]
It does...?

![startmenu](https://cloud.githubusercontent.com/assets/3239942/6083336/612ccb6a-ae02-11e4-8fc2-5b6ac80bab90.png)
![desktop entry](https://cloud.githubusercontent.com/assets/3239942/6083341/6c7c7bbe-ae02-11e4-96a0-4ccad47b46c9.png)

**Comment by smarquespt** [comment]
It happens just the same as I´ve told in #28. I have an user account withou admin previlegies. I install photoqt with that user and start menu/desktop entry are not created for that account. But if I login with admin account the start menu/desktop entries are there

**Comment by luspi** [comment]
Okay, I figured out what's going on with that:
I explicitely request admin rights at the start of the installer script. I thought this is necessary in order to write the application files to C:\Program Files\PhotoQt. However, this had the side effect, that the rest of the installer assumed that the actual administrator is running the installer. Thus, the start menu entry and the desktop icon were always created, but only for the administrator account.

There are two possible solutions:
1) Don't request any special privileges explicitely, the installer will still ask for them, but only to move the files, and the rest is properly created for the current user.
The disadvantage is, that the actual application files are installed under C:\Program Files (x86)\PhotoQt (by default), so all users could access them anyways, but don't have any icons or entries set.
2) Keep explicitely asking for admin rights for the whole installer, but in each of the sections/functions doing stuff with moving files and writing ro the registry, use the command "SetShellVarContext all" to create entries for all users (admin and non-admin).

I think the second way is the better way, the former would only be a half-baken solution (all users would be able to see the actual files but don't know until they explicitely look).

The solution to this, is to simply not request any execution level explicitely. Then, the installer will request admin rights for moving the files, but assumed user rights for the rest. Result: The start menu entry and desktop icon are created for the current user.

**Comment by smarquespt** [comment]
Fixed with latest installer.
