### ISSUE TITLE
windows installer marked as virus

### ISSUE THREAD

**Issue by janpipek** [luspi/photoqt-dev#38]
Dear Lukas,

my avast free antivirus reports the installer to be suspicious of Win32.Evo-gen virus. It may be a false positive (it has happened once also with my own software). Still I recommend you pay attention to it and check that the web has not been contamined. In any case, other users with the same antivirus may be reluctant to install photoqt (I am).

Jan

**Comment by luspi** [comment]
Hi Jan,

Thanks for letting me know. I just ran a scan on it myself, and it didn't find anything (though I'm using Avira Free Antivirus)...

I do recall, that it once did detect the setup file of v1.1 as suspicious, but that was due to an outdated library of the antivirus (after an update, it didn't find anything suspicious anymore)...

**Comment by luspi** [comment]
https://forum.avast.com/index.php?topic=165611.0

It seems to be rather common problem, but (according to the forum post) it should have been fixed in the Avast database 9 days ago...
