### ISSUE TITLE
Switching direction when scrolling with mouse wheel

### ISSUE THREAD

**Issue by SammysHP** [luspi/photoqt-dev#40]
I've added two shortcuts:

- Previous image: Wheel Up
- Next image: Wheel Down

Mouse wheel sensitivity is on its lowest setting (or its highest? leftmost, "Äußerst empfindlich").

Now open a directory of images and scroll down. For each "click" the next image is shown, so far so good.
Now try to go to the previous image by scrolling up. It needs two clicks. Then a single click is enough to get to following previous image. Now change the direction again, scroll down. First two clicks are necessary again, then a single click is enough.

**Comment by luspi** [comment]
Thanks for letting me know, @SammysHP 

The fix was very simple: e72b9c381aebbb97cfce5bdd325a480e28d5bec0
PhotoQt reset the 'click counter' whenever the direction of the wheel movement changed. It is supposed to do that, however, if the wheel sensitivity was set to '1' ('Äußerst empfindlich'), then the first scroll in a direction caused PhotoQt to reset the counter, store the new direction and ignore the event.
Now it skips this check for a sensitivity of 1, and thus doesn't ignore any clicks anymore.

Thanks again for reporting!

**Comment by KOT040188** [comment]
На PhotoQt 1.2 баг по прежнему присутствует…

**Comment by SammysHP** [comment]
@KOT040188 
Because 1.2 is older than the bug report and the fix.

**Comment by luspi** [comment]
@KOT040188 

As @SammysHP already pointed out, the fix is currently only in the code here on GitHub. Version 1.2 for Ubuntu (if I remember correctly, you said you're using Kubuntu?) is packaged by someone else after each new release. So, unfortunately I'm not able to update the package in that repository (Also: I don't use Ubuntu, and never packaged anything for it).

My main focus currently is on porting PhotoQt from Qt/QWidgets to Qt/QML (both areobviously based on C++/Qt, but QML makes creating the interface so much easier). Thus, there wont be a new major release of PhotoQt based on the code in this repository anymore (the QML port is in the repository [photoqt-qml-dev](https://github.com/luspi/photoqt-qml-dev)).

However, I will release a bug fix release 1.2.1 some time over the next weeks, which will include all the fixes and changes so far in this repository here. It usually only takes around two days after this for the ubuntu package in the repository to get updated.

**Comment by KOT040188** [comment]
Спасибо! После исправления этих багов, PhotoQt будет почти идеальным приложением для просмотра изображений =)

**Comment by KOT040188** [comment]
Thank U! After fixing these bugs, PhotoQt will be almost the perfect application for viewing images =)
