### ISSUE TITLE
Thumbnails are not rotated based on EXIF

### ISSUE THREAD

**Issue by muzso** [luspi/photoqt-dev#49]
Using v1.2 thumbnails are not rotated based on the angle stored in the EXIF info of a JPEG image. If I select the image, the fullscreen view is properly rotated (if this is set in settings), just the thumbnails are not.

(I didn't see this issue among the known problems of v1.2 and I didn't see this among old (closed or still open) issues here on GitHub either.)

I'm using Photoqt from Sam's PPA. The exact package version is 1.2~trusty~ppa1 (amd64).
The OS is Ubuntu 14.04.2.

I've "ExifRotation=Always" set in the "[Exif]" section of my settings file.

I can provide a sample image (I've seen this behaviour with JPG files shot with a Nikon D300 camera) if it helps, but I suspect this is a generic problem and not specific for a certain kind of JPG images.

**Comment by luspi** [comment]
That's right, PhotoQt doesn't check the Exif data for thumbnails. The thinking behind this was, that this would slow down the thumbnail creation quite a bit, and thus I opted to ignore it.

There are two possible improvements that can be done for this:
1) Add an option to enable checking the Exif info for each thumbnail
2) Update the thumbnail when the full image is loaded and Exif info is found

I'll probably first will give the first one a try, as the second one requires some larger changes in the thumbnail handling. There will be a release of PhotoQt v1.2.1 coming up in the near future, however, that'll only contain very few bug fixes. I'm currently porting PhotoQt to Qt/QML (you can find the code here: https://github.com/luspi/photoqt-qml-dev), and I'm planning to release a first beta of PhotoQt v1.3 based on this at the same time as v1.2.1.
This improvement probably wont be added to v1.2.1 (as then I would have to do it twice, since the thumbnail handling is completely different in both versions), but I'm hoping to have it up and running for v1.3...

**Comment by muzso** [comment]
Thanks for the quick reply! :-) An easy workaround is to simply rotate the images based on the Exif orientation field. Using "exiftran -aip *.jpg" does a lossless rotation on the jpg files inplace and keeps most (99%) Exif tags intact. Of course after you apply this transformation, you've to clear the PhotoQt thumbnail database too.

As for your proposed options: I prefer the first one too. :-) Having thumbnails with wrong orientation even for a short time would be quite annoying.

**Comment by luspi** [comment]
Yes, unfortunately that's the (probably only) workaround for the moment...

**Comment by luspi** [comment]
Okay, good news: The "rotate at image load according to Exif data" feature just made it into the QML port: luspi/photoqt-qml-dev@48cc77002b6baba5e08f201d45a314f87e5a5e87

I wont be adding it to the current QWidget based code (which v1.2 is based on), so you wont find it in its last release (which will be v1.2.1), but it will be there in v1.3. I plan to release v1.2.1 and v.1.3BETA at the same time, probably within the next month or so... The final v1.3 (including this one and many other changes) will then be coming some time after that (depends on how the beta works out, but I guess somewhere around another month later)...

**Comment by luspi** [comment]
PhotoQt is moving away from GitHub to GitLab ([more info](http://photoqt.org/news/1434375887)). This issue is duplicated here: https://gitlab.com/luspi/photoqt-legacy/issues
