### ISSUE TITLE
When the cursor is hidden by a unclutter, the mouse wheel does not scroll the image.

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-dev#52]
When the cursor is hidden by a unclutter, the mouse wheel does not scroll the image. photoqt 1.2.1 kubuntu 14.04

**Comment by luspi** [comment]
Thanks for reporting! However, version 1.2.1 is EOL (end of life) of the QWidget based version of PhotoQt, it doesn't get any bug fixes anymore. All further development will solely be focussed on the new version (based on QML) that is now officially in beta status: https://gitlab.com/luspi/photoqt
Anyways, I'm not sure what you mean by "hidden by a unclutter"? If you explain that, I can check if the problem also/still exists in v1.3beta...

**Comment by KOT040188** [comment]
I use google translator. unclutter is a console application to automatically hide the cursor. Version 1.2.1 only now appeared in the repository kubuntu 14.04. It is a pity that so late version ...

**Comment by luspi** [comment]
Oh, didn't know about "unclutter" yet... It works on my machine, but I'll see if I get a test kubuntu up and running to see what's going on there...

**Comment by luspi** [comment]
(Sorry for not replying earlier...)
I tried kubuntu 14.04 (via Live CD), installed photoqt 1.2.1 and unclutter and set mouse wheel as shortcut for switching between images. And it works just fine, no problems caused by the cursor being hidden by unclutter... If this issue is still happening, try running photoqt from a terminal (I think it's called "gnome-terminal"), with the "--v" flag (i.e.: run 'photoqt --v', but of course without the single quotation marks). You will get a lot of output at first. After loading a folder, try to switch between images with the mouse wheel. Do you see any new output in the terminal?
