### ISSUE TITLE
EXIF rotation causes image displacement

### ISSUE THREAD

**Issue by Soukyuu** [luspi/photoqt-dev#54]
Just updated to latest git, there seems to be a problem with jpegs rotated via EXIF.

When opening the first rotated jpg everything is fine, but if the next jpg after that has to be rotated as well, the image will be still rotated and scaled correctly, but the positioning on the screen is wrong, with the center being shifted towards the bottom.

It almost feels as if you're setting the top offset based on the upper edge of the scaled image _pre-rotation_ instead of top offset of the center post-rotation. I don't know why it works for the first image, but not if the next one has to be rotated as well...

**Comment by Soukyuu** [comment]
The misbehavior was also present on my older snapshot (e5a9c09), so me updating was to test if it's been fixed already.

**Comment by luspi** [comment]
Hi @Soukyuu 

Thanks for reporting!
Yes, there have been indeed quite a few little bugs in the latest release of PhotoQt. The past release also marked the EOL of the current code basis, and thus there wont be any new bug fixes in this code basis. Over the past few months I've been porting PhotoQt over to QML. Besides the advantages to the GUI, this chance to rework the entire code basis allowed me to take care of as many bugs as I was able to find. You can find the new code over at GitLab: https://gitlab.com/luspi/photoqt

I initially planned to release the new version tomorrow, however, due to some problems in getting an executable for Windows compiled, it'll probably be delayed a few days... I also just checked, the bug you mentioned does not occur anymore in the new code.

**Comment by Soukyuu** [comment]
Yes, I can confirm that. Good work.
