### ISSUE TITLE
Zoom beyond 200%-300% is ugly (blurred)

### ISSUE THREAD

**Issue by 0ion9** [luspi/photoqt-dev#56]
Beyond 300% zoom, interpolation pretty much makes the image into a blurry mess. This is true for all types of image, but has especially bad effect for images that contain crisp lines.

**Comment by luspi** [comment]
Hi @0ion9 
For the interpolation of images I'm currently using the stuff that ships with Qt itself. It's certainly not perfect (which is, e.g., why I don't load the full image right away but always a scaled down version, as otherwise bad interpolation kicks in). It might be a good idea to have a look around for maybe some libraries or ways to improve that generally in PhotoQt...

**Comment by luspi** [comment]
Btw, as I already mentioned in the other issue, for the latest development code (which is v1.3 and beyond), you need to head over to GitLab: https://gitlab.com/luspi/photoqt

**Comment by 0ion9** [comment]
I can re-file these issues there if you want.
BTW, the solution seems like it might be quite simple : http://stackoverflow.com/questions/17692900/qt-c-resize-pixmap-and-keep-pixelation

**Comment by luspi** [comment]
As I wrote in the other issue, no need for that, lets stay here with these two issues (if anything new comes up, though, file them on GitLab).

Well, actually, I already use the suggestion from the stackoverflow question: When you load a large image, I first properly scale it down (similarly to the way suggested there) before displaying it. I do this (1) exactly because of the observed problem of messy interpolation, and (2) for faster image loading.

A while ago I did once experiment with doing this on a larger scale, i.e., instead of increasing the displayed size of an image, to first properly scale it to the new size and then re-set the image. However, this is incredibly slow (image scaling works reasonably well, of the scaled image is small, but becomes noticeably slower for larger scaled image sizes).

Now, I did such experiments well before I even thought of switching to QML. Maybe there's a better solution to the whole interpolation issue now... I'll check it out and let you know!

**Comment by luspi** [comment]
Okay, what I did now was to [completely rewrite the image display and management engine](https://gitlab.com/luspi/photoqt/commit/fba227a25c9494a166cfd1b8a8a40217d56df66c) in PhotoQt. The old one was still very similar to the one as PhotoQt was based on QWidgets, and for QWidgets I had to not only take care of everything manually, but I also had to add quite a few tweaks to get something suable. Now, I let QML handle most of the interpolation stuff and it seems to be doing a pretty good job at it, the interpolations appears to be a lot smoother than before. Of course, I'll have to do a little more testing with the new solution to make sure that it really does work as expected, but it certainly seems to be already working a lot better than the old one ever has...

If you're able to check it out, let me know what you think!

**Comment by 0ion9** [comment]
I would consider #55 fixed now, zoom speed is quite good even on very small images. #56 appears to be unchanged (interpolation(==blur) is still happening beyond 200-300% zoom)

**Comment by luspi** [comment]
Well, it is impossible to not have any blurring happening when an image is zoomed in beyond its resolution. That's simply a law of rate and sampling (if I recall correctly from one of my Undergraduate classes, this phenomenon is captured in the [Nyquist–Shannon sampling theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem). I'll have a look around if there is maybe a better algorithm that can be used in Qt/QML to get a little better quality, but I'm not very confident that that'll be possible...

The issue with animated images was my mistake, I forgot that the handling of the sourceSize property is slightly different for animated images. [That should be fixed now.](https://gitlab.com/luspi/photoqt/commit/32e46fb14da1f9b4438ca325060e31ec46710db3)

**Comment by 0ion9** [comment]
> Well, it is impossible to not have any blurring happening when an image is zoomed in beyond its resolution. That's simply a law of rate and sampling

That's incorrect. Nearest-neighbour does not blur.

**Comment by luspi** [comment]
Okay I see what you mean. And for small images (like the one you posted in the other issue) I think it does make sense to interpolate using the 'Nearest Neighbour' algorithm. For upscaling, I personally still prefer using mipmaps for better quality, though that might be just a matter of taste.

Anyways, I added two new options (in the settings, tab 'Look and Feel', sub-tab 'Advanced', near the bottom) where you can adjust two things:
1) The size threshold below which size PhotoQt will always use 'Nearest Neighbour' interpolation (e.g., a setting of 100px (current default) means that any image smaller than 100x100 will be displayed using 'Nearest Neighbour')
2) A checkbox to set 'Nearest Neighbour' for upscaling, i.e., zooming past the actual image size. This one I have set to disabled by default, so you first need to change it if you want to use it.

**Comment by 0ion9** [comment]
Thanks.

> For upscaling, I personally still prefer using mipmaps for better quality, though that might be just a matter of taste.

Well, this is why I specified 200-300%. The limitations of the interpolation algorithm are not severely obvious at small scales, it's only at larger scales that there is obviously more blur than information. All of the interpolation algorithms that do a decent job of avoiding blur (HQ2x/3x/4x; xBR) are relatively specialized, such that they don't work particularly well for photographs; and/or slow ([vector scaling](http://inkscape.org), [Neural network scaling](http://waifu2x.udp.jp/)) or proprietary (fractal scaling)

Anyway, I won't be using option 1 personally, but I will certainly try 2. Rebuilding now.

**Comment by luspi** [comment]
That's why I said it's a "matter of taste". I really do prefer having some blur but somewhat smooth lines when zooming in a lot over having a highly pixelated image display...

Let me know if you encounter any problems!

**Comment by 0ion9** [comment]
I updated but didn't need to set the option 2 -- it appeared to already be using NN-upscaling, both for small and large (eg 640x480px) images. Checking the 'Mipmaps and NN' section, the settings say '100px' and the 'use NN for upscaling' checkbox was not checked. So I think there might be a bug in the logic there.

Putting that aside, it works very nicely now from my POV. The way it continues to animate during the zooming process is pretty good, I hadn't noticed that before. 

I think there may be another minor bug with GIFs though, as the metadata display often shows "Invalid File" rather than the image dimensions and filesize. There is also [this variation](http://i.imgur.com/yNYJnsf.png), which I **think** is displaying both 'Invalid file' and 'No file loaded' at the same time -- produced by [this file](). I can open a separate issue for that on gitlab if you want.

BTW, are you aware lang/photoqt_*.ts are versioned? Because these files are updated by the build process (for some reason. I thought build/ was supposed to fully isolate the build process?), I always have to run `git reset --hard HEAD` before pulling the latest changes.

**Comment by luspi** [comment]
Indeed, the 'Nearest Neighbour' upscaling switch had a little logical flaw in it, [it should be working fine now](https://gitlab.com/luspi/photoqt/commit/34e308ffa08816fc8bc44d55c052d2d13029cb07).

Ha, thanks for pointing out the gif problem. Somebody mentioned it to me before that they encountered a problem like this, but they didn't know which file (or fileformat) caused it for them. No need to open an issue for that, [it's now fixed](https://gitlab.com/luspi/photoqt/commit/ee5a241c3bfef4c9d722ccdf5c9cfadb1592b1b5), too (including another bug in decoding the path when it contained non-Latin characters).

Well, updating the *.ts files is indeed done on purpose when running cmake in order to generate the *.qm files that are needed for the internal translation engine. I didn't consider that this might cause problems for pulling changes. [I have now updated the CMakeLists.txt](https://gitlab.com/luspi/photoqt/commit/cf7a008eb347063e5d1db8bd6c2f1e4fa0064526) to first copy all the *.ts files to the build folder before processing them. That way, the source language files are left untouched.
